### ISSUE TITLE
卡下载上了，selenium  chromedriver已安装 py3.74

### ISSUE THREAD

**Issue by barnett2010** [Algebra-FUN/WeReadScan#16]
![2021-07-07_001101](https://user-images.githubusercontent.com/8305408/124634827-4b8d7100-de76-11eb-8806-f0a62a58d41a.jpg)
如图

**Comment by barnett2010** [comment]
chrome 版本90.0.4430.212

**Comment by barnett2010** [comment]
我搜索到了一个说法 
错误信息：Passthrough is not supported, GL is swiftshader

解决方法：

错误信息Passthrough is not supported, GL is swiftshader可能是在 Chromedriver 版本 89 之后显示的错误信息。

使用chromedriver时，一般都需要指定--headless和--disable-gpu参数，可以不显示浏览器的窗口，如果不使用这两个选项，则不会出现错误消息。

也可以使用--disable-software-rasterizer 参数，禁用 WebGL，在不显示窗口的模式下，也不显示错误消息。

**Comment by barnett2010** [comment]
于是，我在 headless那一行，加个# 注释掉

运行，会弹出浏览器窗口，自动开始执行了。

**Comment by barnett2010** [comment]
![2021-07-07_004537](https://user-images.githubusercontent.com/8305408/124637735-a4aad400-de79-11eb-9fb1-9c5ddb2ac022.jpg)

但是发现，下载没有全下完

**Comment by barnett2010** [comment]
我把chrome driver 都换成了低版本 81
然后demo.py不动
运行，就还是依然卡在弹不出二维码登录上
![image](https://user-images.githubusercontent.com/8305408/124639358-978ee480-de7b-11eb-80a7-32094dce3501.png)

**Comment by barnett2010** [comment]
注释掉chrome_options.add_argument('--headless')  #! important argument 
就可以，

会弹出浏览器，一页一页 在自动翻

**Comment by barnett2010** [comment]
可不可以导txt。不导pdf。感觉pdf有点费时

**Comment by Algebra-FUN** [comment]
### 关于 headless 的问题
使用 headless 模式 可以比较便捷的截取网页全部内容
如果是有窗体模式，则只会截取显示的部分（虽然也可以通过滑窗在拼合，但是实现起来比较复杂）

### 关于导出PDF而不是TXT文本格式的问题
本脚本通过截图，进行下载，下载的是图片文件
微信读书通过“Canvas上绘制的文字”的方法进行反爬虫，所以无法直接获取文字（也有可行方案，但是实现起来比较繁琐）
