### ISSUE TITLE
CSS 选择器使用了新版 Selenium 弃用的方法

### ISSUE THREAD

**Issue by ShengrongYang** [Algebra-FUN/WeReadScan#21]
Selenium 4.3.0+ 版本弃用了 WebDriver 对象的 find_element_by_* 方法，由统一的 find_element 方法替代。因此 WeRead.py 中的 CSS 选择器可能改成`self.driver.find_element(By.CSS_SELECTOR, 'css_selector')`比较合适，不然会报 AttributeError。

**Comment by Algebra-FUN** [comment]
已在最新版本中解决
