### ISSUE TITLE
截图

### ISSUE THREAD

**Issue by sunboy123** [Algebra-FUN/WeReadScan#3]
我也想把自己看过的书导出成pdf的可惜加密了，您的采用截图的方法很好，但是图片处理的二值化之后图像显示很差，最为关键的是截屏不完整，这是个很严重的bug

**Comment by Algebra-FUN** [comment]
其实截图本身就不是最佳解决方案，由于微信读书采用canvas绘制文字和字节流加密的方法进行反爬，所以解决思路主要两种：

1. 破解其字节流加密（破解有一定难度）
2. canvas转图片；

而事实上canvas绘制文字本来就会造成图像质量差（浏览器缩放和也会变糊），之前有用过js inject的方式进行canvas转img，但是效果并不好。

如果有其他更好的解决思路，欢迎交流讨论！Thanks for your issue.
