### ISSUE TITLE
登陆后无法运行

### ISSUE THREAD

**Issue by HRITW** [Algebra-FUN/WeReadScan#38]
请问扫码登陆之后出现如下的错误是什么原因呢？
StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: headless chrome=114.0.5735.199)

**Comment by RemyHaijie** [comment]
同样的问题，求解决
Scanning the book:"机器学习算法的数学解析与Python实现"                                                                                                                      Traceback (most recent call last):                                                                                                                                            File "C:\Users\remychen\Downloads\WeReadScan-html-variant\WeReadScan-html-variant\example\demo.py", line 30, in <module>                                                      weread.scan2html('https://weread.qq.com/web/reader/2c632ef071a486a92c60226kc81322c012c81e728d9d180')                                                                      File "D:\software\Python\Lib\site-packages\WeReadScan\WeRead.py", line 189, in scan2html                                                                                      html = self.get_html(book_url)                                                                                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                            File "D:\software\Python\Lib\site-packages\WeReadScan\WeRead.py", line 163, in get_html                                                                                       readerFooterClass = readerFooter.get_attribute('class')                                                                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                   File "D:\software\Python\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 178, in get_attribute                                                               attribute_value = self.parent.execute_script(                                                                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                             File "D:\software\Python\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 406, in execute_script                                                               return self.execute(command, {"script": script, "args": converted_args})["value"]                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                  File "D:\software\Python\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute                                                                      self.error_handler.check_response(response)                                                                                                                               File "D:\software\Python\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response                                                            raise exception_class(message, screen, stacktrace)                                                                                                                      selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found                                                          (Session info: headless chrome=115.0.5790.102); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception                                                                                                                                              Stacktrace:                                                                                                                                                                 Backtrace:

**Comment by Algebra-FUN** [comment]
在最新的WeReadScan-HTML v0.1.1中已经解决该问题, 欢迎下载最新版本
```shell
pip install WeReadScan-HTML==0.1.1
```
